In [3]:
import pandas as pd

In [17]:
df = pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [18]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [19]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [20]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [21]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [22]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [24]:
df[['Name', 'Sex', 'Cabin', 'Embarked']]

                                                  Name     Sex Cabin Embarked
0                              Braund, Mr. Owen Harris    male   NaN        S
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female   C85        C
2                                Heikkinen, Miss Laina  female   NaN        S
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  C123        S
4                             Allen, Mr. William Henry    male   NaN        S
..                                                 ...     ...   ...      ...
886                              Montvila, Rev. Juozas    male   NaN        S
887                        Graham, Miss Margaret Edith  female   B42        S
888            Johnston, Miss Catherine Helen "Carrie"  female   NaN        S
889                              Behr, Mr. Karl Howell    male  C148        C
890                                Dooley, Mr. Patrick    male   NaN        Q

[891 rows x 4 columns]

In [25]:
df.dtypes == 'object'

PassengerId    False
Survived       False
Pclass         False
Name            True
Sex             True
Age            False
SibSp          False
Parch          False
Ticket          True
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [26]:
df.dtypes == 'int'

PassengerId     True
Survived        True
Pclass          True
Name           False
Sex            False
Age            False
SibSp           True
Parch           True
Ticket         False
Fare           False
Cabin          False
Embarked       False
dtype: bool

In [27]:
df.dtypes == 'float'

PassengerId    False
Survived       False
Pclass         False
Name           False
Sex            False
Age             True
SibSp          False
Parch          False
Ticket         False
Fare            True
Cabin          False
Embarked       False
dtype: bool

In [28]:
df[df.dtypes[df.dtypes == 'float64'].index]

      Age     Fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [29]:
df[df.dtypes[df.dtypes == 'int64'].index]

     PassengerId  Survived  Pclass  SibSp  Parch
0              1         0       3      1      0
1              2         1       1      1      0
2              3         1       3      0      0
3              4         1       1      1      0
4              5         0       3      0      0
..           ...       ...     ...    ...    ...
886          887         0       2      0      0
887          888         1       1      0      0
888          889         0       3      1      2
889          890         1       1      0      0
890          891         0       3      0      0

[891 rows x 5 columns]

In [30]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [31]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [32]:
df[['Ticket']]

               Ticket
0           A/5 21171
1            PC 17599
2    STON/O2. 3101282
3              113803
4              373450
..                ...
886            211536
887            112053
888        W./C. 6607
889            111369
890            370376

[891 rows x 1 columns]

In [33]:
#Slicing
df[['Ticket']][4:16]

       Ticket
4      373450
5      330877
6       17463
7      349909
8      347742
9      237736
10    PP 9549
11     113783
12  A/5. 2151
13     347082
14     350406
15     248706

In [35]:
df[['Ticket']][4:16:2]

       Ticket
4      373450
6       17463
8      347742
10    PP 9549
12  A/5. 2151
14     350406

In [38]:
df[['Ticket','Cabin']][4:17:2]

       Ticket Cabin
4      373450   NaN
6       17463   E46
8      347742   NaN
10    PP 9549    G6
12  A/5. 2151   NaN
14     350406   NaN
16     382652   NaN

In [44]:
#New_c0lumn
df['Murshid'] = 2

In [45]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,Murshid
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,2
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,2,2
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,2,2
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,2,2
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,2,2
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,2,2
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,2,2

In [46]:
df.insert(loc = 3, column = 'Food', value = 0)

In [47]:
df

,PassengerId,Survived,Pclass,Food,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,Murshid
0,1,0,3,0,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2,2
1,2,1,1,0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,2
2,3,1,3,0,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,2,2
3,4,1,1,0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2,2
4,5,0,3,0,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,0,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,2,2
887,888,1,1,0,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,2,2
888,889,0,3,0,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,2,2
889,890,1,1,0,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,2,2
890,891,0,3,0,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,2,2

In [48]:
df.insert(loc = 6, column = 'Equipments', value = "Oxygen Cylinder")

In [49]:
df

,PassengerId,Survived,Pclass,Food,Name,Sex,Equipments,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,Murshid
0,1,0,3,0,"Braund, Mr. Owen Harris",male,Oxygen Cylinder,22.0,1,0,A/5 21171,7.2500,NaN,S,2,2
1,2,1,1,0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,Oxygen Cylinder,38.0,1,0,PC 17599,71.2833,C85,C,2,2
2,3,1,3,0,"Heikkinen, Miss Laina",female,Oxygen Cylinder,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,2,2
3,4,1,1,0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,Oxygen Cylinder,35.0,1,0,113803,53.1000,C123,S,2,2
4,5,0,3,0,"Allen, Mr. William Henry",male,Oxygen Cylinder,35.0,0,0,373450,8.0500,NaN,S,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,0,"Montvila, Rev. Juozas",male,Oxygen Cylinder,27.0,0,0,211536,13.0000,NaN,S,2,2
887,888,1,1,0,"Graham, Miss Margaret Edith",female,Oxygen Cylinder,19.0,0,0,112053,30.0000,B42,S,2,2
888,889,0,3,0,"Johnston, Miss Catherine Helen ""Carrie""",female,Oxygen Cylinder,NaN,1,2,W./C. 6607,23.4500,NaN,S,2,2
889,890,1,1,0,"Behr, Mr. Karl Howell",male,Oxygen Cylinder,26.0,0,0,111369,30.0000,C148,C,2,2
890,891,0,3,0,"Dooley, Mr. Patrick",male,Oxygen Cylinder,32.0,0,0,370376,7.7500,NaN,Q,2,2

#Part 2

In [51]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                  Heikkinen, Miss Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                          Graham, Miss Margaret Edith
888              Johnston, Miss Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [52]:
df['Name'][0:10]

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                Heikkinen, Miss Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
5                                     Moran, Mr. James
6                              McCarthy, Mr. Timothy J
7                        Palsson, Master Gosta Leonard
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                  Nasser, Mrs. Nicholas (Adele Achem)
Name: Name, dtype: object

In [54]:
a = df['Name'][0:10]

In [55]:
a

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                Heikkinen, Miss Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
5                                     Moran, Mr. James
6                              McCarthy, Mr. Timothy J
7                        Palsson, Master Gosta Leonard
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                  Nasser, Mrs. Nicholas (Adele Achem)
Name: Name, dtype: object

In [56]:
type(a)

pandas.core.series.Series

In [57]:
l = ['Ali', 'a2','a3','a4','a5','a6','a7','a8','a9','a10']

In [59]:
pd.Series(a, index = l)

Ali    NaN
a2     NaN
a3     NaN
a4     NaN
a5     NaN
a6     NaN
a7     NaN
a8     NaN
a9     NaN
a10    NaN
Name: Name, dtype: object

In [60]:
pd.Series(list(a), index = l)

Ali                              Braund, Mr. Owen Harris
a2     Cumings, Mrs. John Bradley (Florence Briggs Th...
a3                                 Heikkinen, Miss Laina
a4          Futrelle, Mrs. Jacques Heath (Lily May Peel)
a5                              Allen, Mr. William Henry
a6                                      Moran, Mr. James
a7                               McCarthy, Mr. Timothy J
a8                         Palsson, Master Gosta Leonard
a9     Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
a10                  Nasser, Mrs. Nicholas (Adele Achem)
dtype: object

In [62]:
m1 = pd.Series([100,200,300,400,500], index = [1,2,3,4,5])

In [63]:
m1

1    100
2    200
3    300
4    400
5    500
dtype: int64

In [64]:
m2 = pd.Series([100,200,300,400,500], index = [1,2,3,4,5])

In [65]:
m2

1    100
2    200
3    300
4    400
5    500
dtype: int64

In [66]:
m3 = pd.concat([m1,m2])

In [67]:
m3

1    100
2    200
3    300
4    400
5    500
1    100
2    200
3    300
4    400
5    500
dtype: int64

In [68]:
m3[1]

1    100
1    100
dtype: int64

In [69]:
m1*m2

1     10000
2     40000
3     90000
4    160000
5    250000
dtype: int64

In [71]:
df

,PassengerId,Survived,Pclass,Food,Name,Sex,Equipments,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,Murshid
0,1,0,3,0,"Braund, Mr. Owen Harris",male,Oxygen Cylinder,22.0,1,0,A/5 21171,7.2500,NaN,S,2,2
1,2,1,1,0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,Oxygen Cylinder,38.0,1,0,PC 17599,71.2833,C85,C,2,2
2,3,1,3,0,"Heikkinen, Miss Laina",female,Oxygen Cylinder,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,2,2
3,4,1,1,0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,Oxygen Cylinder,35.0,1,0,113803,53.1000,C123,S,2,2
4,5,0,3,0,"Allen, Mr. William Henry",male,Oxygen Cylinder,35.0,0,0,373450,8.0500,NaN,S,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,0,"Montvila, Rev. Juozas",male,Oxygen Cylinder,27.0,0,0,211536,13.0000,NaN,S,2,2
887,888,1,1,0,"Graham, Miss Margaret Edith",female,Oxygen Cylinder,19.0,0,0,112053,30.0000,B42,S,2,2
888,889,0,3,0,"Johnston, Miss Catherine Helen ""Carrie""",female,Oxygen Cylinder,NaN,1,2,W./C. 6607,23.4500,NaN,S,2,2
889,890,1,1,0,"Behr, Mr. Karl Howell",male,Oxygen Cylinder,26.0,0,0,111369,30.0000,C148,C,2,2
890,891,0,3,0,"Dooley, Mr. Patrick",male,Oxygen Cylinder,32.0,0,0,370376,7.7500,NaN,Q,2,2

In [78]:
df.drop("PassengerId", axis = 1)

,Survived,Pclass,Food,Name,Sex,Equipments,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,Murshid
0,0,3,0,"Braund, Mr. Owen Harris",male,Oxygen Cylinder,22.0,1,0,A/5 21171,7.2500,NaN,S,2,2
1,1,1,0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,Oxygen Cylinder,38.0,1,0,PC 17599,71.2833,C85,C,2,2
2,1,3,0,"Heikkinen, Miss Laina",female,Oxygen Cylinder,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,2,2
3,1,1,0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,Oxygen Cylinder,35.0,1,0,113803,53.1000,C123,S,2,2
4,0,3,0,"Allen, Mr. William Henry",male,Oxygen Cylinder,35.0,0,0,373450,8.0500,NaN,S,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,0,"Montvila, Rev. Juozas",male,Oxygen Cylinder,27.0,0,0,211536,13.0000,NaN,S,2,2
887,1,1,0,"Graham, Miss Margaret Edith",female,Oxygen Cylinder,19.0,0,0,112053,30.0000,B42,S,2,2
888,0,3,0,"Johnston, Miss Catherine Helen ""Carrie""",female,Oxygen Cylinder,NaN,1,2,W./C. 6607,23.4500,NaN,S,2,2
889,1,1,0,"Behr, Mr. Karl Howell",male,Oxygen Cylinder,26.0,0,0,111369,30.0000,C148,C,2,2
890,0,3,0,"Dooley, Mr. Patrick",male,Oxygen Cylinder,32.0,0,0,370376,7.7500,NaN,Q,2,2

In [79]:
df.head()

,PassengerId,Survived,Pclass,Food,Name,Sex,Equipments,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,Murshid
0,1,0,3,0,"Braund, Mr. Owen Harris",male,Oxygen Cylinder,22.0,1,0,A/5 21171,7.2500,NaN,S,2,2
1,2,1,1,0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,Oxygen Cylinder,38.0,1,0,PC 17599,71.2833,C85,C,2,2
2,3,1,3,0,"Heikkinen, Miss Laina",female,Oxygen Cylinder,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,2,2
3,4,1,1,0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,Oxygen Cylinder,35.0,1,0,113803,53.1000,C123,S,2,2
4,5,0,3,0,"Allen, Mr. William Henry",male,Oxygen Cylinder,35.0,0,0,373450,8.0500,NaN,S,2,2

In [82]:
df.drop("Survived", axis = 1, inplace = True)

In [83]:
df

,PassengerId,Pclass,Food,Name,Sex,Equipments,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,Murshid
0,1,3,0,"Braund, Mr. Owen Harris",male,Oxygen Cylinder,22.0,1,0,A/5 21171,7.2500,NaN,S,2,2
1,2,1,0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,Oxygen Cylinder,38.0,1,0,PC 17599,71.2833,C85,C,2,2
2,3,3,0,"Heikkinen, Miss Laina",female,Oxygen Cylinder,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,2,2
3,4,1,0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,Oxygen Cylinder,35.0,1,0,113803,53.1000,C123,S,2,2
4,5,3,0,"Allen, Mr. William Henry",male,Oxygen Cylinder,35.0,0,0,373450,8.0500,NaN,S,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,2,0,"Montvila, Rev. Juozas",male,Oxygen Cylinder,27.0,0,0,211536,13.0000,NaN,S,2,2
887,888,1,0,"Graham, Miss Margaret Edith",female,Oxygen Cylinder,19.0,0,0,112053,30.0000,B42,S,2,2
888,889,3,0,"Johnston, Miss Catherine Helen ""Carrie""",female,Oxygen Cylinder,NaN,1,2,W./C. 6607,23.4500,NaN,S,2,2
889,890,1,0,"Behr, Mr. Karl Howell",male,Oxygen Cylinder,26.0,0,0,111369,30.0000,C148,C,2,2
890,891,3,0,"Dooley, Mr. Patrick",male,Oxygen Cylinder,32.0,0,0,370376,7.7500,NaN,Q,2,2

In [84]:
df.head()

,PassengerId,Pclass,Food,Name,Sex,Equipments,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,Murshid
0,1,3,0,"Braund, Mr. Owen Harris",male,Oxygen Cylinder,22.0,1,0,A/5 21171,7.2500,NaN,S,2,2
1,2,1,0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,Oxygen Cylinder,38.0,1,0,PC 17599,71.2833,C85,C,2,2
2,3,3,0,"Heikkinen, Miss Laina",female,Oxygen Cylinder,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,2,2
3,4,1,0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,Oxygen Cylinder,35.0,1,0,113803,53.1000,C123,S,2,2
4,5,3,0,"Allen, Mr. William Henry",male,Oxygen Cylinder,35.0,0,0,373450,8.0500,NaN,S,2,2

In [85]:
df.drop(3, inplace = True)

In [86]:
df

,PassengerId,Pclass,Food,Name,Sex,Equipments,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,Murshid
0,1,3,0,"Braund, Mr. Owen Harris",male,Oxygen Cylinder,22.0,1,0,A/5 21171,7.2500,NaN,S,2,2
1,2,1,0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,Oxygen Cylinder,38.0,1,0,PC 17599,71.2833,C85,C,2,2
2,3,3,0,"Heikkinen, Miss Laina",female,Oxygen Cylinder,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,2,2
4,5,3,0,"Allen, Mr. William Henry",male,Oxygen Cylinder,35.0,0,0,373450,8.0500,NaN,S,2,2
5,6,3,0,"Moran, Mr. James",male,Oxygen Cylinder,NaN,0,0,330877,8.4583,NaN,Q,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,2,0,"Montvila, Rev. Juozas",male,Oxygen Cylinder,27.0,0,0,211536,13.0000,NaN,S,2,2
887,888,1,0,"Graham, Miss Margaret Edith",female,Oxygen Cylinder,19.0,0,0,112053,30.0000,B42,S,2,2
888,889,3,0,"Johnston, Miss Catherine Helen ""Carrie""",female,Oxygen Cylinder,NaN,1,2,W./C. 6607,23.4500,NaN,S,2,2
889,890,1,0,"Behr, Mr. Karl Howell",male,Oxygen Cylinder,26.0,0,0,111369,30.0000,C148,C,2,2
890,891,3,0,"Dooley, Mr. Patrick",male,Oxygen Cylinder,32.0,0,0,370376,7.7500,NaN,Q,2,2

In [88]:
df.set_index('Name', inplace = True)

In [89]:
df

,PassengerId,Pclass,Food,Sex,Equipments,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,Murshid
Name,,,,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,3,0,male,Oxygen Cylinder,22.0,1,0,A/5 21171,7.2500,NaN,S,2,2
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,0,female,Oxygen Cylinder,38.0,1,0,PC 17599,71.2833,C85,C,2,2
"Heikkinen, Miss Laina",3,3,0,female,Oxygen Cylinder,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,2,2
"Allen, Mr. William Henry",5,3,0,male,Oxygen Cylinder,35.0,0,0,373450,8.0500,NaN,S,2,2
"Moran, Mr. James",6,3,0,male,Oxygen Cylinder,NaN,0,0,330877,8.4583,NaN,Q,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Montvila, Rev. Juozas",887,2,0,male,Oxygen Cylinder,27.0,0,0,211536,13.0000,NaN,S,2,2
"Graham, Miss Margaret Edith",888,1,0,female,Oxygen Cylinder,19.0,0,0,112053,30.0000,B42,S,2,2
"Johnston, Miss Catherine Helen ""Carrie""",889,3,0,female,Oxygen Cylinder,NaN,1,2,W./C. 6607,23.4500,NaN,S,2,2
"Behr, Mr. Karl Howell",890,1,0,male,Oxygen Cylinder,26.0,0,0,111369,30.0000,C148,C,2,2
"Dooley, Mr. Patrick",891,3,0,male,Oxygen Cylinder,32.0,0,0,370376,7.7500,NaN,Q,2,2

In [90]:
df.reset_index()

,Name,PassengerId,Pclass,Food,Sex,Equipments,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,Murshid
0,"Braund, Mr. Owen Harris",1,3,0,male,Oxygen Cylinder,22.0,1,0,A/5 21171,7.2500,NaN,S,2,2
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,0,female,Oxygen Cylinder,38.0,1,0,PC 17599,71.2833,C85,C,2,2
2,"Heikkinen, Miss Laina",3,3,0,female,Oxygen Cylinder,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,2,2
3,"Allen, Mr. William Henry",5,3,0,male,Oxygen Cylinder,35.0,0,0,373450,8.0500,NaN,S,2,2
4,"Moran, Mr. James",6,3,0,male,Oxygen Cylinder,NaN,0,0,330877,8.4583,NaN,Q,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,"Montvila, Rev. Juozas",887,2,0,male,Oxygen Cylinder,27.0,0,0,211536,13.0000,NaN,S,2,2
886,"Graham, Miss Margaret Edith",888,1,0,female,Oxygen Cylinder,19.0,0,0,112053,30.0000,B42,S,2,2
887,"Johnston, Miss Catherine Helen ""Carrie""",889,3,0,female,Oxygen Cylinder,NaN,1,2,W./C. 6607,23.4500,NaN,S,2,2
888,"Behr, Mr. Karl Howell",890,1,0,male,Oxygen Cylinder,26.0,0,0,111369,30.0000,C148,C,2,2
889,"Dooley, Mr. Patrick",891,3,0,male,Oxygen Cylinder,32.0,0,0,370376,7.7500,NaN,Q,2,2

In [ ]:
Make dataframe from the dictionary

In [91]:
d = {"key1" : [1,2,3,4,5],
     "key2" : [6,7,8,9,10],
     "key3" : [11,12,13,14,15]
    }

In [92]:
print(d)

{'key1': [1, 2, 3, 4, 5], 'key2': [6, 7, 8, 9, 10], 'key3': [11, 12, 13, 14, 15]}

In [93]:
pd.DataFrame(d)

   key1  key2  key3
0     1     6    11
1     2     7    12
2     3     8    13
3     4     9    14
4     5    10    15

In [ ]:
df1 = pd.read_csv("taxanomy.csv")